# Generated by Django 3.0.8 on 2020-07-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20200707_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
